from snakemake.exceptions import MissingInputException
import os
from os.path import join

_author__ = "Sebastian Kurscheid (sebastian.kurscheid@anu.edu.au)"
__license__ = "MIT"
__date__ = "2017-11-01"

rule:
    version: 1

localrules:
    all

# variables
home_dir = os.environ['HOME']
home = home_dir

# include functions
include:
    "scripts/common/input_functions.py"
include:
    "scripts/common/parameter_functions.py"

REF_GENOME = "hg38"
REF_VERSION = config["references"][REF_GENOME]["version"][1]

# build targets
rule all:
    input:
        expand("{assayID}/{file}.bw",
                assayID="ChIP-Seq",
                file=["merged/" + config["processed_dir"] + "/" + REF_VERSION + "/deepTools/bamCoverage/normal/RPKM/duplicates_removed/"  + j \
                    for j in config["samples"]["ChIP-Seq"]["replicates"].keys()])

include:
    "./rules/mergeBam.smk"