from snakemake.exceptions import MissingInputException
import os
from os.path import join

_author__ = "Sebastian Kurscheid (sebastian.kurscheid@anu.edu.au)"
__license__ = "MIT"
__date__ = "2017-11-01"

rule:
    version: 1

localrules:
    all

# variables
home_dir = os.environ['HOME']
home = home_dir

# include functions
include:
    "scripts/common/input_functions.py"
include:
    "scripts/common/parameter_functions.py"

REF_GENOME = "hg38"
REF_VERSION = config["references"][REF_GENOME]["version"][1]

# build targets
rule all:
    input:
        expand("{assayID}/{file}.bw",
                assayID="ChIP-Seq",
                file=["merged/" + config["processed_dir"] + "/" + REF_VERSION + "/deepTools/bamCoverage/normal/RPKM/duplicates_removed/"  + j \
                    for j in config["samples"]["ChIP-Seq"]["replicates"].keys()])

rule all_bigwigcompare:
        expand("{assayID}/{runID}/{outdir}/{reference_version}/{application}/{tool}/{mode}/{norm}/{duplicates}/{contrast}/{ratio}/{condition}.bw",
               assayID="ChIP-Seq",
               runID="merged",
               outdir=config["processed_dir"],
               reference_version=REF_VERSION,
               application=["deepTools"],
               tool=["bigwigCompare"],
               mode=["normal"],
               norm=["RPKM"],
               duplicates=["duplicates_removed"],
               contrast=["ChIP-Input"],
               ratio="log2",
               condition=["MCF10A_WT_HP1a",
                          "MCF10A_WT_HP1b",
                          "MCF10A_WT_H2AZ",
                          "MCF10A_shHP1a_HP1b",
                          "MCF10A_shHP1b_HP1a",
                          "MCF10A_shH2AZ_HP1a",
                          "MCF10A_shH2AZ_HP1b"])
                          
include:
    "./rules/mergeBam.smk"